using System.Collections.Generic;
using System.Xml.Serialization;

namespace ResRobot
{
    /// <summary>
    /// Namespace for storing information when searching for trip between two locations. Autogenerated for easier parsing. 
    /// </summary>
    namespace XmlTripsClass
    {
        [XmlRoot(ElementName = "ServiceDays", Namespace = "hafas_rest_v1")]
        public class ServiceDays
        {
            [XmlAttribute(AttributeName = "sDaysR")]
            public string SDaysR { get; set; }
            [XmlAttribute(AttributeName = "sDaysI")]
            public string SDaysI { get; set; }
            [XmlAttribute(AttributeName = "sDaysB")]
            public string SDaysB { get; set; }
            [XmlAttribute(AttributeName = "planningPeriodBegin")]
            public string PlanningPeriodBegin { get; set; }
            [XmlAttribute(AttributeName = "planningPeriodEnd")]
            public string PlanningPeriodEnd { get; set; }
        }

        [XmlRoot(ElementName = "Origin", Namespace = "hafas_rest_v1")]
        public class Origin
        {
            [XmlAttribute(AttributeName = "extId")]
            public string ExtId { get; set; }
            [XmlAttribute(AttributeName = "id")]
            public string Id { get; set; }
            [XmlAttribute(AttributeName = "name")]
            public string Name { get; set; }
            [XmlAttribute(AttributeName = "type")]
            public string Type { get; set; }
            [XmlAttribute(AttributeName = "lon")]
            public string Lon { get; set; }
            [XmlAttribute(AttributeName = "lat")]
            public string Lat { get; set; }
            [XmlAttribute(AttributeName = "date")]
            public string Date { get; set; }
            [XmlAttribute(AttributeName = "time")]
            public string Time { get; set; }
        }

        [XmlRoot(ElementName = "Destination", Namespace = "hafas_rest_v1")]
        public class Destination
        {
            [XmlAttribute(AttributeName = "extId")]
            public string ExtId { get; set; }
            [XmlAttribute(AttributeName = "id")]
            public string Id { get; set; }
            [XmlAttribute(AttributeName = "name")]
            public string Name { get; set; }
            [XmlAttribute(AttributeName = "type")]
            public string Type { get; set; }
            [XmlAttribute(AttributeName = "lon")]
            public string Lon { get; set; }
            [XmlAttribute(AttributeName = "lat")]
            public string Lat { get; set; }
            [XmlAttribute(AttributeName = "date")]
            public string Date { get; set; }
            [XmlAttribute(AttributeName = "time")]
            public string Time { get; set; }
        }

        [XmlRoot(ElementName = "Leg", Namespace = "hafas_rest_v1")]
        public class Leg
        {
            [XmlElement(ElementName = "Origin", Namespace = "hafas_rest_v1")]
            public Origin Origin { get; set; }
            [XmlElement(ElementName = "Destination", Namespace = "hafas_rest_v1")]
            public Destination Destination { get; set; }
            [XmlAttribute(AttributeName = "type")]
            public string Type { get; set; }
            [XmlAttribute(AttributeName = "idx")]
            public string Idx { get; set; }
            [XmlAttribute(AttributeName = "dist")]
            public string Dist { get; set; }
            [XmlAttribute(AttributeName = "duration")]
            public string Duration { get; set; }
            [XmlAttribute(AttributeName = "name")]
            public string Name { get; set; }
            [XmlElement(ElementName = "Product", Namespace = "hafas_rest_v1")]
            public Product Product { get; set; }
            [XmlElement(ElementName = "Stops", Namespace = "hafas_rest_v1")]
            public Stops Stops { get; set; }
            [XmlAttribute(AttributeName = "transportNumber")]
            public string TransportNumber { get; set; }
            [XmlAttribute(AttributeName = "transportCategory")]
            public string TransportCategory { get; set; }
            [XmlAttribute(AttributeName = "reachable")]
            public string Reachable { get; set; }
            [XmlAttribute(AttributeName = "direction")]
            public string Direction { get; set; }
            [XmlElement(ElementName = "Notes", Namespace = "hafas_rest_v1")]
            public Notes Notes { get; set; }
        }

        [XmlRoot(ElementName = "Product", Namespace = "hafas_rest_v1")]
        public class Product
        {
            [XmlAttribute(AttributeName = "catCode")]
            public string CatCode { get; set; }
            [XmlAttribute(AttributeName = "catOutL")]
            public string CatOutL { get; set; }
            [XmlAttribute(AttributeName = "catOutS")]
            public string CatOutS { get; set; }
            [XmlAttribute(AttributeName = "name")]
            public string Name { get; set; }
            [XmlAttribute(AttributeName = "num")]
            public string Num { get; set; }
            [XmlAttribute(AttributeName = "operator")]
            public string Operator { get; set; }
            [XmlAttribute(AttributeName = "operatorCode")]
            public string OperatorCode { get; set; }
            [XmlAttribute(AttributeName = "operatorUrl")]
            public string OperatorUrl { get; set; }
        }

        [XmlRoot(ElementName = "Stop", Namespace = "hafas_rest_v1")]
        public class Stop
        {
            [XmlAttribute(AttributeName = "depDate")]
            public string DepDate { get; set; }
            [XmlAttribute(AttributeName = "depTime")]
            public string DepTime { get; set; }
            [XmlAttribute(AttributeName = "routeIdx")]
            public string RouteIdx { get; set; }
            [XmlAttribute(AttributeName = "name")]
            public string Name { get; set; }
            [XmlAttribute(AttributeName = "id")]
            public string Id { get; set; }
            [XmlAttribute(AttributeName = "extId")]
            public string ExtId { get; set; }
            [XmlAttribute(AttributeName = "lon")]
            public string Lon { get; set; }
            [XmlAttribute(AttributeName = "lat")]
            public string Lat { get; set; }
            [XmlAttribute(AttributeName = "arrDate")]
            public string ArrDate { get; set; }
            [XmlAttribute(AttributeName = "arrTime")]
            public string ArrTime { get; set; }
        }

        [XmlRoot(ElementName = "Stops", Namespace = "hafas_rest_v1")]
        public class Stops
        {
            [XmlElement(ElementName = "Stop", Namespace = "hafas_rest_v1")]
            public List<Stop> Stop { get; set; }
        }

        [XmlRoot(ElementName = "Note", Namespace = "hafas_rest_v1")]
        public class Note
        {
            [XmlAttribute(AttributeName = "routeIdxFrom")]
            public string RouteIdxFrom { get; set; }
            [XmlAttribute(AttributeName = "routeIdxTo")]
            public string RouteIdxTo { get; set; }
            [XmlAttribute(AttributeName = "key")]
            public string Key { get; set; }
            [XmlAttribute(AttributeName = "priority")]
            public string Priority { get; set; }
            [XmlAttribute(AttributeName = "type")]
            public string Type { get; set; }
            [XmlText]
            public string Text { get; set; }
        }

        [XmlRoot(ElementName = "Notes", Namespace = "hafas_rest_v1")]
        public class Notes
        {
            [XmlElement(ElementName = "Note", Namespace = "hafas_rest_v1")]
            public List<Note> Note { get; set; }
        }

        [XmlRoot(ElementName = "LegList", Namespace = "hafas_rest_v1")]
        public class LegList
        {
            [XmlElement(ElementName = "Leg", Namespace = "hafas_rest_v1")]
            public List<Leg> Leg { get; set; }
        }

        [XmlRoot(ElementName = "Trip", Namespace = "hafas_rest_v1")]
        public class Trip
        {
            [XmlElement(ElementName = "ServiceDays", Namespace = "hafas_rest_v1")]
            public ServiceDays ServiceDays { get; set; }
            [XmlElement(ElementName = "LegList", Namespace = "hafas_rest_v1")]
            public LegList LegList { get; set; }
            [XmlAttribute(AttributeName = "idx")]
            public string Idx { get; set; }
            [XmlAttribute(AttributeName = "ctxRecon")]
            public string CtxRecon { get; set; }
            [XmlAttribute(AttributeName = "tripId")]
            public string TripId { get; set; }
            [XmlAttribute(AttributeName = "duration")]
            public string Duration { get; set; }
        }

        [XmlRoot(ElementName = "TripList", Namespace = "hafas_rest_v1")]
        public class TripList
        {
            [XmlElement(ElementName = "Trip", Namespace = "hafas_rest_v1")]
            public List<Trip> Trip { get; set; }
            [XmlAttribute(AttributeName = "xmlns")]
            public string Xmlns { get; set; }
            [XmlAttribute(AttributeName = "scrB")]
            public string ScrB { get; set; }
            [XmlAttribute(AttributeName = "scrF")]
            public string ScrF { get; set; }
        }
        
    }
}
